name: angel_task
version: 1.0.0
description: Support for running asynchronous jobs within Angel. Ideal for large applications.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/task
dependencies:
  angel_common: ^1.0.0-beta
  pool: ^1.3.0
  sync: ^0.1.0
  uuid: ^0.5.3
dev_dependencies:
  test: ^0.12.0