name: angel_task
version: 1.1.1
description: Support for running asynchronous jobs within Angel. Ideal for large applications.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/task
dependencies:
  angel_framework: ^1.0.0
  uuid: ^0.5.3
dev_dependencies:
  mock_request: ^1.0.0
  test: ^0.12.0